name: qfvpn
description: A vpn application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  provider: ^5.0.0

  flutter_bloc: ^7.0.0

  http: ^0.13.0

  http_interceptor: ^0.4.0

  equatable: ^2.0.0

  rxdart: ^0.26.0

  infinite_scroll_pagination: ^3.0.1

  json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0

  json_serializable: ^4.0.0

flutter:
  uses-material-design: true

  # use plugin [FlutterImageSync] https://github.com/Leo0618/flutter-img-sync
  assets:
    - images/img_login_bg.png
    - images/btn_radio_n.png
    - images/ico_vip_n.png
    - images/btn_next_n.png
    - images/btn_soso_n.png
    - images/ico_eye.png
    - images/btn_notgood_n.png
    - images/btn_next_white_p.png
    - images/img_service.png
    - images/btn_back_n.png
    - images/icon_opinion.png
    - images/ico_lock.png
    - images/ico_eyeslash_1.png
    - images/btn_copy_p.png
    - images/ico_mail.png
    - images/btn_imgdelete_p.png
    - images/icon_about.png
    - images/ico_warning_red.png
    - images/ico_ailpay_seleted.png
    - images/ico_home_n.png
    - images/img_rocket.png
    - images/btn_dropdown_n.png
    - images/btn_camera_p.png
    - images/btn_setting_p.png
    - images/ico_mail_2.png
    - images/btn_close_n.png
    - images/icon_help.png
    - images/img_speed.png
    - images/btn_back_white_n.png
    - images/ico_mail_1.png
    - images/ico_power.png
    - images/img_empty.png
    - images/btn_share_n.png
    - images/btn_sogood_n.png
    - images/ico_emoji_1.png
    - images/ico_shieldcheck.png
    - images/ico_ailpay_seleted_2.png
    - images/btn_history_n.png
    - images/ico_my_n.png
    - images/ico_emoji_2.png
    - images/ico_warning_white.png
    - images/img_animation_red.png
    - images/icon_notice.png
    - images/btn_camera_n.png
    - images/img_animation_circle.png
    - images/ico_handshake_1.png
    - images/btn_setting_n.png
    - images/img_earnpoint.png
    - images/ellipse_11.png
    - images/btn_close_p.png
    - images/ico_eyeslash.png
    - images/btn_back_white_p.png
    - images/img_vip.png
    - images/btn_share_p.png
    - images/btn_sogood_p.png
    - images/ico_broadcast.png
    - images/ico_wechatpay.png
    - images/ico_invite_gift.png
    - images/img_coupon_used.png
    - images/btn_history_p.png
    - images/ico_my_p.png
    - images/eye.png
    - images/ico_invite_friends.png
    - images/ico_power_big.png
    - images/ico_vip_p.png
    - images/btn_radio_p.png
    - images/btn_next_p.png
    - images/img_safety.png
    - images/btn_soso_p.png
    - images/ico_step_gift.png
    - images/img_animation_blue.png
    - images/eye_slash.png
    - images/img_special.png
    - images/ico_ailpay.png
    - images/img_gift.png
    - images/ico_deferment.png
    - images/ico_wechatpay_selected.png
    - images/btn_notgood_p.png
    - images/btn_next_white_n.png
    - images/btn_back_p.png
    - images/img_coupon_use.png
    - images/img_success.png
    - images/icon_linked.png
    - images/ico_lock_2.png
    - images/img_fill.png
    - images/ico_signal_1.png
    - images/ico_handshake.png
    - images/ico_eye_1.png
    - images/ico_close.png
    - images/btn_copy_n.png
    - images/btn_imgdelete_n.png
    - images/ico_signal_3.png
    - images/ico_lock_1.png
    - images/ico_home_p.png
    - images/icon_link.png
    - images/ico_signal_2.png
    - images/btn_dropdown_p.png
    - images/ico_success.png
