import 'package:flutter/material.dart';

import '../r.dart';

class FlagResMap {
  AssetImage get(String country) {
    switch (country.toLowerCase()) {
      case 'lt':
        return R.image.flag_lithuania();
      case 'mc':
        return R.image.flag_monaco();
      case 'it':
        return R.image.flag_italy();
      case 'ko':
        return R.image.flag_kosovo();
      case 'lv':
        return R.image.flag_latvia();
      case 'lu':
        return R.image.flag_luxembourg();
      case 'is':
        return R.image.flag_iceland();
      case 'ie':
        return R.image.flag_ireland();
      case 'li':
        return R.image.flag_liechtenstein();
      case 'gg':
        return R.image.flag_guernsey();
      case 'hu':
        return R.image.flag_hungary();
      case 'de':
        return R.image.flag_germany();
      case 'fr':
        return R.image.flag_france();
      case 'gi':
        return R.image.flag_gibraltar();
      case 'fi':
        return R.image.flag_finland();
      case 'fo':
        return R.image.flag_faroe_islands();
      case 'gr':
        return R.image.flag_greece();
      case 'ee':
        return R.image.flag_estonia();
      case 'al':
        return R.image.flag_albania();
      case 'ad':
        return R.image.flag_andorra();
      case 'at':
        return R.image.flag_austria();
      case 'by':
        return R.image.flag_belarus();
      case 'be':
        return R.image.flag_belgium();
      case 'bg':
        return R.image.flag_bulgaria();
      case 'cz':
        return R.image.flag_czech_republic();
      case 'dk':
        return R.image.flag_denmark();
      case 'nl':
        return R.image.flag_netherlands();
      case 'no':
        return R.image.flag_norway();
      case 'mk':
        return R.image.flag_macedonia();
      case 'pl':
        return R.image.flag_poland();
      case 'ro':
        return R.image.flag_romania();
      case 'rs':
        return R.image.flag_serbia();
      case 'sk':
        return R.image.flag_slovakia();
      case 'es':
        return R.image.flag_spain();
      case 'se':
        return R.image.flag_sweden();
      case 'ch':
        return R.image.flag_switzerland();
      case 'ua':
        return R.image.flag_ukraine();
      case 'mq':
        return R.image.flag_martinique();
      case 'mx':
        return R.image.flag_mexico();
      case 'ht':
        return R.image.flag_haiti();
      case 'hi':
        return R.image.flag_hawaii();
      case 'gy':
        return R.image.flag_guyana();
      case 'hn':
        return R.image.flag_honduras();
      case 'gt':
        return R.image.flag_guatemala();
      case 'jm':
        return R.image.flag_jamaica();
      case 'gd':
        return R.image.flag_grenada();
      case 'gl':
        return R.image.flag_greenland();
      case 'fk':
        return R.image.flag_falkland_islands();
      case 'aw':
        return R.image.flag_aruba();
      case 'as':
        return R.image.flag_american_samoa();
      case 'ar':
        return R.image.flag_argentina();
      case 'bo':
        return R.image.flag_bolivia();
      case 'ky':
        return R.image.flag_cayman_islands();
      case 'bs':
        return R.image.flag_bahamas();
      case 'bm':
        return R.image.flag_bermuda();
      case 'br':
        return R.image.flag_brazil();
      case 'ca':
        return R.image.flag_canada();
      case 'cl':
        return R.image.flag_chile();
      case 'co':
        return R.image.flag_colombia();
      case 'cr':
        return R.image.flag_costa_rica();
      case 'ec':
        return R.image.flag_ecuador();
      case 'cu':
        return R.image.flag_cuba();
      case 'do':
        return R.image.flag_dominican_republic();
      case 'ni':
        return R.image.flag_nicaragua();
      case 'pr':
        return R.image.flag_puerto_rico();
      case 'pe':
        return R.image.flag_peru();
      case 'pt':
        return R.image.flag_portugal();
      case 'pa':
        return R.image.flag_panama();
      case 'kn':
        return R.image.flag_saint_kitts_and_nevis();
      case 'vc':
        return R.image.flag_st_vincent_and_the_grenadines();
      case 'us':
        return R.image.flag_america();
      case 'py':
        return R.image.flag_paraguay();
      case 'sv':
        return R.image.flag_salvador();
      case 'mf':
        return R.image.flag_sint_maarten();
      case 'tt':
        return R.image.flag_trinidad_and_tobago();
      case 'uy':
        return R.image.flag_uruguay();
      case 've':
        return R.image.flag_venezuela();
      case 'kw':
        return R.image.flag_kuwait();
      case 'mn':
        return R.image.flag_mongolia();
      case 'mo':
        return R.image.flag_macao();
      case 'mm':
        return R.image.flag_myanmar();
      case 'il':
        return R.image.flag_israel();
      case 'lb':
        return R.image.flag_lebanon();
      case 'kz':
        return R.image.flag_kazakhstan();
      case 'my':
        return R.image.flag_malaysia();
      case 'iq':
        return R.image.flag_iraq();
      case 'jo':
        return R.image.flag_jordan();
      case 'mv':
        return R.image.flag_maldives();
      case 'ir':
        return R.image.flag_iran();
      case 'jp':
        return R.image.flag_japan();
      case 'id':
        return R.image.flag_indonesia();
      case 'in':
        return R.image.flag_india();
      case 'hk':
        return R.image.flag_hong_kong();
      case 'eg':
        return R.image.flag_egypt();
      case 'np':
        return R.image.flag_nepal();
      case 'kp':
        return R.image.flag_north_korea();
      case 'om':
        return R.image.flag_oman();
      case 'ps':
        return R.image.flag_palestine();
      case 'ph':
        return R.image.flag_philippines();
      case 'pk':
        return R.image.flag_pakistan();
      case 'ru':
        return R.image.flag_russia();
      case 'sa':
        return R.image.flag_saudi_arabia();
      case 'sg':
        return R.image.flag_singapore();
      case 'kr':
        return R.image.flag_south_korea();
      case 'lk':
        return R.image.flag_sri_lanka();
      case 'sy':
        return R.image.flag_syria();
      case 'tw':
        return R.image.flag_taiwan();
      case 'th':
        return R.image.flag_thailand();
      case 'tm':
        return R.image.flag_turkmenistan();
      case 'uz':
        return R.image.flag_uzbekistn();
      case 'vn':
        return R.image.flag_vietnam();
      case 'tr':
        return R.image.flag_turkey();
      case 'la':
        return R.image.flag_laos();
      case 'cn':
        return R.image.flag_china();
      case 'kh':
        return R.image.flag_cambodia();
      default:
        return R.image.flag_auto();
    }
  }
}
